name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base=4.3
  - r-seurat
  - r-remotes
  - r-reticulate
  - r-matrix
  - anndata
  - scanpy
  - mudata
  - plotnine
  - pandas
  - numpy
  - liana
